# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name tracking-barbell-exercises > environment.yml
#    conda env remove --name tracking-barbell-exercises
#    conda env list

name: env
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11.5
  - pip
  - bottleneck
  - pip:
      - numpy==1.24.3
      - pandas==2.0.3
      - ipykernel==6.25.0 
      - ipython==8.15.0  
      - jupyter-client==7.4.9
      - jupyter-core== 5.3.0  
      - matplotlib==3.7.2  
      - scipy==1.11.3


